name: Pull Request Labeler

on:
  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Labeling
        uses: actions/labeler@v5
        with:
          sync-labels: true
