name: Create release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Create Release Pull Request or Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          # Expects a script called release that builds the packages and calls changeset publish
          publish: pnpm changeset tag
          version: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  release-tag:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Create release
        env:
          VERSION: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$VERSION" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${VERSION#v}" \
          --generate-notes
