name: Create release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Create Release Pull Request or Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          # Expects a script called release that builds the packages and calls changeset publish
          publish: pnpm changeset tag
          version: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
